package:
  name: tangram_{{ cookiecutter.project_slug }}
  version: {{ '{{' }} environ.get('GIT_DESCRIBE_TAG', 'v')[1:] {{ '}}' }}

source:
  path: ../

build:
  number: {{ '{{' }} environ.get('GIT_DESCRIBE_NUMBER', '0')|int {{ '}}' }}
  script: "{{ '{{' }} PYTHON {{ '}}' }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - pychimera     >=0.2.6
    - libtangram

about:
  home: http://github.com/insilichem/tangram_{{cookiecutter.project_slug}}
  license: {{cookiecutter.open_source_license}}
  license_family: {{cookiecutter.open_source_license_family}}

  summary: '{{cookiecutter.project_description}}'

  description: |
    {{cookiecutter.project_description}}
  doc_url: http://tangram-suite.readthedocs.io/en/latest/tangram_{{cookiecutter.project_slug}}.html
  dev_url: https://github.com/insilichem/tangram_{{cookiecutter.project_slug}}
